"""empty message

Revision ID: 59133f9d28ee
Revises: 36f3940c13be
Create Date: 2026-04-17 15:26:45.654049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59133f9d28ee'
down_revision = '36f3940c13be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_variants', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('has_variants')

    # ### end Alembic commands ###
