"""add is primary to ProductImage Model

Revision ID: 6b1d65233977
Revises: c7a178765e9a
Create Date: 2026-03-04 21:37:27.194823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1d65233977'
down_revision = 'c7a178765e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
