"""empty message

Revision ID: c66e8fd6186c
Revises: 1f1d0a75b7b5
Create Date: 2026-04-03 20:02:17.608205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66e8fd6186c'
down_revision = '1f1d0a75b7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_location', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
